### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by graiolo** [FunghiFannoBene/mishell-fedmarti#2]
# TITOLO

ls | exit | ls -- leaks (solo con exit?)
no controllo sulla creazione del file
ls > file1 > file2 [...]
ls << CIAO (ordine inveritto)
exit non stampa exit

echo $USER$USER
exit

diff file1 file2 | wc < file2
cat << EOF >> 1 < 2
ls | ls |
"
'

**Comment by fedmarti** [comment]
Grazie per aver collaborato al progetto.
Il contributo è stato apprezzato profondamente.
